name: Code Check

on:
  push:
    branches: ['main', 'staging', 'dev']
  pull_request:
    branches: ['main', 'staging', 'dev']

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: 🔬 Lint
        run: pnpm lint:strict

      - name: 🔎 Type check
        run: pnpm typecheck

      - name: 💅 Prettier check
        run: pnpm format:check
